import React from 'react';

const data = [
  {
    title: 'MLH Hackcon',
    pic: '/assets/pic.jpg',
    venue: 'New Delhi, India',
    date: '25 Sept 2022',
    maxCap: '200',
    attendees: '80',
    time: '10am - 5pm',
  },
  {
    title: 'MLH Hackcon',
    pic: '/assets/pic.jpg',
    venue: 'New Delhi, India',
    date: '25 Sept 2022',
    maxCap: '200',
    attendees: '80',
    time: '10am - 5pm',
  },
  {
    title: 'MLH Hackcon',
    pic: '/assets/pic.jpg',
    venue: 'New Delhi, India',
    date: '25 Sept 2022',
    maxCap: '200',
    attendees: '80',
    time: '10am - 5pm',
  },
  {
    title: 'MLH Hackcon',
    pic: '/assets/pic.jpg',
    venue: 'New Delhi, India',
    date: '25 Sept 2022',
    maxCap: '200',
    attendees: '80',
    time: '10am - 5pm',
  },
  {
    title: 'MLH Hackcon',
    pic: '/assets/pic.jpg',
    venue: 'New Delhi, India',
    date: '25 Sept 2022',
    maxCap: '200',
    attendees: '80',
    time: '10am - 5pm',
  },
  {
    title: 'MLH Hackcon',
    pic: '/assets/pic.jpg',
    venue: 'New Delhi, India',
    date: '25 Sept 2022',
    maxCap: '200',
    attendees: '80',
    time: '10am - 5pm',
  },
  {
    title: 'MLH Hackcon',
    pic: '/assets/pic.jpg',
    venue: 'New Delhi, India',
    date: '25 Sept 2022',
    maxCap: '200',
    attendees: '80',
    time: '10am - 5pm',
  },
  {
    title: 'MLH Hackcon',
    pic: '/assets/pic.jpg',
    venue: 'New Delhi, India',
    date: '25 Sept 2022',
    maxCap: '200',
    attendees: '80',
    time: '10am - 5pm',
  },
  {
    title: 'MLH Hackcon',
    pic: '/assets/pic.jpg',
    venue: 'New Delhi, India',
    date: '25 Sept 2022',
    maxCap: '200',
    attendees: '80',
    time: '10am - 5pm',
  },
  {
    title: 'MLH Hackcon',
    pic: '/assets/pic.jpg',
    venue: 'New Delhi, India',
    date: '25 Sept 2022',
    maxCap: '200',
    attendees: '80',
    time: '10am - 5pm',
  },
  {
    title: 'MLH Hackcon',
    pic: '/assets/pic.jpg',
    venue: 'New Delhi, India',
    date: '25 Sept 2022',
    maxCap: '200',
    attendees: '80',
    time: '10am - 5pm',
  },
  {
    title: 'MLH Hackcon',
    pic: '/assets/pic.jpg',
    venue: 'New Delhi, India',
    date: '25 Sept 2022',
    maxCap: '200',
    attendees: '80',
    time: '10am - 5pm',
  },
];

export default data;
