const data = [
  {
    title: 'MLH Hackcon',
    pic: '/images/event-bg3.jpg',
    venue: 'London',
    date: '25 Sept 2022',
    maxCap: '200',
    attendees: '80',
    time: '10am onwards',
  },
  {
    title: 'Dandiya Night',
    pic: '/images/event-bg1.jpg',
    venue: 'New Delhi, India',
    date: '25 Sept 2022',
    maxCap: '200',
    attendees: '80',
    time: '10am onwards',
  },
  {
    title: 'MLH Hackcon',
    pic: '/images/event-bg.jpg',
    venue: 'New Delhi, India',
    date: '25 Sept 2022',
    maxCap: '200',
    attendees: '80',
    time: '10am onwards',
  },
  {
    title: 'MLH Hackcon',
    pic: '/images/event-bg2.jpg',
    venue: 'New Delhi, India',
    date: '25 Sept 2022',
    maxCap: '200',
    attendees: '80',
    time: '10am onwards',
  },
  {
    title: 'MLH Hackcon',
    pic: '/images/event-bg.jpg',
    venue: 'New Delhi, India',
    date: '25 Sept 2022',
    maxCap: '200',
    attendees: '80',
    time: '10am onwards',
  },
  {
    title: 'MLH Hackcon',
    pic: '/images/event-bg3.jpg',
    venue: 'New Delhi, India',
    date: '25 Sept 2022',
    maxCap: '200',
    attendees: '80',
    time: '10am onwards',
  },
  {
    title: 'MLH Hackcon',
    pic: '/images/event-bg2.jpg',
    venue: 'New Delhi, India',
    date: '25 Sept 2022',
    maxCap: '200',
    attendees: '80',
    time: '10am onwards',
  },
  {
    title: 'MLH Hackcon',
    pic: '/images/event-bg1.jpg',
    venue: 'New Delhi, India',
    date: '25 Sept 2022',
    maxCap: '200',
    attendees: '80',
    time: '10am onwards',
  },
  {
    title: 'MLH Hackcon',
    pic: '/images/event-bg2.jpg',
    venue: 'New Delhi, India',
    date: '25 Sept 2022',
    maxCap: '200',
    attendees: '80',
    time: '10am onwards',
  },
  {
    title: 'MLH Hackcon',
    pic: '/images/event-bg1.jpg',
    venue: 'New Delhi, India',
    date: '25 Sept 2022',
    maxCap: '200',
    attendees: '80',
    time: '10am onwards',
  },
  {
    title: 'MLH Hackcon',
    pic: '/images/event-bg3.jpg',
    venue: 'New Delhi, India',
    date: '25 Sept 2022',
    maxCap: '200',
    attendees: '80',
    time: '10am onwards',
  },
  {
    title: 'MLH Hackcon',
    pic: '/images/event-bg.jpg',
    venue: 'New Delhi, India',
    date: '25 Sept 2022',
    maxCap: '200',
    attendees: '80',
    time: '10am onwards',
  },
];

export default data;
