const data = [
  {
    id: 1,
    title: 'MLH Hackcon',
    pic: '/images/event-bg2.jpg',
    venue: 'New Delhi, India',
    date: '25 Sept 2022',
    maxCap: '200',
    attendees: '80',
    time: '10am onwards',
  },
  {
    id: 2,
    title: 'Dandiya Night',
    pic: '/images/event-bg1.jpg',
    venue: 'New Delhi, India',
    date: '25 Sept 2022',
    maxCap: '200',
    attendees: '80',
    time: '10am onwards',
  },
  {
    id: 3,
    title: 'MLH Hackcon',
    pic: '/images/event-bg.jpg',
    venue: 'New Delhi, India',
    date: '25 Sept 2022',
    maxCap: '200',
    attendees: '80',
    time: '10am onwards',
  },
  {
    id: 4,
    title: 'MLH Hackcon',
    pic: '/images/event-bg1.jpg',
    venue: 'New Delhi, India',
    date: '25 Sept 2022',
    maxCap: '200',
    attendees: '80',
    time: '10am onwards',
  },
  {
    id: 5,
    title: 'MLH Hackcon',
    pic: '/images/event-bg.jpg',
    venue: 'New Delhi, India',
    date: '25 Sept 2022',
    maxCap: '200',
    attendees: '80',
    time: '10am onwards',
  },
  {
    id: 6,
    title: 'MLH Hackcon',
    pic: '/images/event-bg2.jpg',
    venue: 'New Delhi, India',
    date: '25 Sept 2022',
    maxCap: '200',
    attendees: '80',
    time: '10am onwards',
  },
  {
    id: 7,
    title: 'MLH Hackcon',
    pic: '/images/event-bg2.jpg',
    venue: 'New Delhi, India',
    date: '25 Sept 2022',
    maxCap: '200',
    attendees: '80',
    time: '10am onwards',
  },
  {
    id: 8,
    title: 'MLH Hackcon',
    pic: '/images/event-bg2.jpg',
    venue: 'New Delhi, India',
    date: '25 Sept 2022',
    maxCap: '200',
    attendees: '80',
    time: '10am onwards',
  },
  {
    id: 9,
    title: 'MLH Hackcon',
    pic: '/images/event-bg2.jpg',
    venue: 'New Delhi, India',
    date: '25 Sept 2022',
    maxCap: '200',
    attendees: '80',
    time: '10am onwards',
  },
  {
    id: 10,
    title: 'MLH Hackcon',
    pic: '/images/event-bg2.jpg',
    venue: 'New Delhi, India',
    date: '25 Sept 2022',
    maxCap: '200',
    attendees: '80',
    time: '10am onwards',
  },
  {
    id: 11,
    title: 'MLH Hackcon',
    pic: '/images/event-bg2.jpg',
    venue: 'New Delhi, India',
    date: '25 Sept 2022',
    maxCap: '200',
    attendees: '80',
    time: '10am onwards',
  },
  {
    id: 12,
    title: 'MLH Hackcon',
    pic: '/images/event-bg2.jpg',
    venue: 'New Delhi, India',
    date: '25 Sept 2022',
    maxCap: '200',
    attendees: '80',
    time: '10am onwards',
  },
];

export default data;
